version: '3.1'

services:

  mongodb:
    image: mongo:latest # use the latest image.
    container_name: mongodb
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassmongodb
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080