version: '3.1'

services:

  mysql:
    image: mysql:latest # use the latest image.
    container_name: mysql
    restart: always
    env_file:
      - database.env
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080