version: '3.1'

services:

  mysql:
    image: mysql:latest # use the latest image.
    container_name: mysql
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080