version: '3.1'

services:

  mariadb:
    image: mariadb:latest # use the latest image.
    container_name: mariadb
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassmariadb
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080