version: '3.1'

services:

  mariadb:
    image: mariadb:latest # use the latest image.
    container_name: mariadb
    restart: always
    environment:
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080