version: '3.1'

services:

  mariadb:
    image: mariadb:latest # use the latest image.
    container_name: mariadb
    restart: always
    env_file:
      - database.env
  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8000